name: 03-vite

on:
  schedule:
    - cron: '0 2 * * *' # ron on 2am every day
  push:
    branches:
      - main
    paths:
      - '.github/workflows/03-vite.yml'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/03-vite.yml'
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  vite:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
 
      
      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        
      - name: Pull latest changes
        run: git pull origin main --rebase # 使用 rebase 来避免合并提交
        
      - name: Modify release.md and commit changes
        run: |
          echo "## New Release $(date +"%Y.%m.%d_%H_%M_%S")" >> release.md
          git add release.md
          git commit -m "Update release.md" || echo "No changes to commit"
          
      - name: Push changes
        run: git push origin HEAD:main || echo "Push skipped due to no changes or conflicts"

      - name: Checkout mirror repo
        run: |
          git clone https://github.com/vitejs/vite.git --depth=1

      - name: zip mirror repo source
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r vite-source.zip ./vite
          
      - name: Install pnpm
        uses: pnpm/action-setup@v2.4.1
        with:
          version: 8.12.1

      - name: Set node version to 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          cache: "pnpm"

      - name: add content path
        run: |
          sed -i 's/export default defineConfig({/export default defineConfig({ base: "\/mirror\/vite",/' ./vite/docs/.vitepress/config.ts
          
      - name: build site
        run: |
          cd vite && pnpm install && pnpm run build && pnpm run docs-build
  
      - name: zip zite
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r vite.zip ./vite/docs/.vitepress/dist

      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::vite_$(date +"%Y.%m.%d_%H_%M_%S")"
      - name: GH Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: |
            vite.zip
            vite-source.zip